name: Build All

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Increment version number
        run: ./.github/script/incrementVersion.sh
      - name: Build with Gradle
        run: ./gradlew build test
      - name: Quality analysis
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
          COVERALLS_GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: ./gradlew aggregateJacocoReport coveralls
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: DockerFile creation
        run: |
          docker build -f updatarium-cli/Dockerfile -t saagie/updatarium:latest updatarium-cli/build/distributions
          docker tag saagie/updatarium:latest saagie/updatarium-snapshot:${{ steps.extract_branch.outputs.branch }}
      - name: Docker check image
        run: docker run --rm -v ${PWD}:/updatarium-src saagie/updatarium:latest /updatarium-src/samples/basic-multiplechangelog-withtag/src/main/resources/changelogs
      - name: Docker run tests with and without tags
        run: ./.github/script/testDocker.sh
      - name: Docker push
        run: docker push saagie/updatarium-snapshot:${{ steps.extract_branch.outputs.branch }}